# Generated by Django 6.0.2 on 2026-04-15 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField(help_text='Share your thoughts or memories', max_length=500)),
                ('targetScholar', models.CharField(help_text='Student this comment is for', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Student Comment',
                'verbose_name_plural': 'Student Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Your name', max_length=100)),
                ('sender_email', models.EmailField(blank=True, help_text='Your email (optional, for replies)', max_length=254)),
                ('message', models.TextField(help_text='Your private message', max_length=2000)),
                ('targetScholar', models.CharField(help_text='Student this message is for', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='scholarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name", max_length=100)),
                ('description', models.TextField(help_text='Personal message, achievements, or memories', max_length=1000)),
                ('section', models.CharField(choices=[('Einstein', 'Einstein'), ('Tesla', 'Tesla'), ('Curie', 'Curie')], help_text="Student's section", max_length=50)),
                ('image', models.ImageField(help_text="Student's photo", upload_to='student_photos')),
                ('email', models.EmailField(blank=True, help_text="Student's email (for receiving private messages)", max_length=254)),
                ('graduation_year', models.IntegerField(default=2026)),
                ('favorite_memory', models.TextField(blank=True, help_text='Favorite school memory', max_length=500)),
                ('future_plans', models.CharField(blank=True, help_text='Plans after graduation', max_length=200)),
            ],
            options={
                'verbose_name': 'Batch 2026 Student',
                'verbose_name_plural': 'Batch 2026 Students',
                'ordering': ['section', 'name'],
            },
        ),
    ]
