# Generated by Django 5.1.1 on 2024-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_Title', models.CharField(max_length=200)),
                ('book_Author', models.CharField(max_length=200)),
                ('book_AccNum', models.CharField(max_length=200)),
            ],
        ),
    ]
