# Generated by Django 6.0.2 on 2026-04-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarlist',
            name='dislikes',
            field=models.TextField(blank=True, default='-', help_text='Things the student dislikes', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarlist',
            name='likes',
            field=models.TextField(blank=True, default='-', help_text='Things the student likes', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarlist',
            name='mbti',
            field=models.CharField(blank=True, default='-', help_text="Student's MBTI", max_length=10),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='image',
            field=models.ImageField(default='student_photos/batcher.jpg', help_text="Student's photo", upload_to='student_photos'),
        ),
    ]
