# Generated by Django 5.1.1 on 2024-09-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_books'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='book',
        ),
    ]
