# Generated by Django 6.0.2 on 2026-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_scholarlist_dislikes_scholarlist_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarlist',
            name='dislikes',
            field=models.TextField(blank=True, default='-', help_text='Things the student dislikes', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='favorite_memory',
            field=models.TextField(blank=True, help_text='Favorite school memory', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='future_plans',
            field=models.CharField(blank=True, help_text='Plans after graduation', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='likes',
            field=models.TextField(blank=True, default='-', help_text='Things the student likes', max_length=1000),
        ),
    ]
