# Generated by Django 5.1.1 on 2024-09-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_alter_books_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
