# Generated by Django 5.1.1 on 2024-09-18 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_rename_books_book_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='book_borrowDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reader',
            name='book_name',
            field=models.CharField(default='John Doe', max_length=200),
        ),
        migrations.AddField(
            model_name='reader',
            name='book_returnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
