# Generated by Django 5.1.1 on 2024-10-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0005_reader_book_borrowdate_reader_book_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='reference_id',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='reference_address',
            new_name='reader_address',
        ),
    ]
