# Generated by Django 5.1.1 on 2024-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_rename_reference_id_reader_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_id',
            field=models.CharField(default='No ID Number given', max_length=200),
        ),
    ]
