# Generated by Django 5.1.1 on 2024-10-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0007_reader_reader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_id',
            field=models.CharField(max_length=200),
        ),
    ]
