# Generated by Django 5.1.1 on 2024-11-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0008_alter_reader_book_name_alter_reader_reader_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_Location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
