# Generated by Django 5.1.1 on 2024-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0009_book_book_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.CharField(max_length=200)),
                ('account_contact', models.CharField(max_length=200)),
                ('account_address', models.CharField(max_length=200)),
            ],
        ),
    ]
