# Generated by Django 5.1.1 on 2024-12-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0010_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
