# Generated by Django 5.1.1 on 2024-12-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0011_alter_account_account_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_AccNum',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_Author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_Location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_Title',
            field=models.CharField(max_length=255),
        ),
    ]
