# Generated by Django 5.1.1 on 2024-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0012_book_is_borrowed_alter_book_book_accnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
