# Generated by Django 5.1.6 on 2025-02-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0013_book_borrow_date_book_borrowed_by_book_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_contact',
        ),
    ]
