# Generated by Django 5.1.6 on 2025-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0014_remove_account_account_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_batch',
            field=models.TextField(default='e.g. 2026', max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_address',
            field=models.TextField(default='e.g. example@gmail.com'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='13-2020-052', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='Bright Bastasa', max_length=100, unique=True),
        ),
    ]
