# Generated by Django 5.1.6 on 2025-04-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0015_account_account_batch_alter_account_account_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_Author',
            new_name='book_mainAuthor',
        ),
        migrations.AddField(
            model_name='book',
            name='book_Editors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_Publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_coAuthor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_copyrightDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_placeofPublication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_publicationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
