# Generated by Django 5.2 on 2025-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0016_rename_book_author_book_book_mainauthor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_Editors',
            new_name='Editors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_Location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_Publisher',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_Title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_AccNum',
            new_name='accessionNumber',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_coAuthor',
            new_name='coAuthor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_copyrightDate',
            new_name='copyrightDate',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_mainAuthor',
            new_name='mainAuthor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_placeofPublication',
            new_name='placeofPublication',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_publicationDate',
            new_name='publicationDate',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='book_borrowDate',
            new_name='borrowDate',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='book_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='book_returnDate',
            new_name='returnDate',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='book_id',
        ),
        migrations.AddField(
            model_name='book',
            name='Language',
            field=models.CharField(default='English', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='Type',
            field=models.CharField(choices=[('Analytics', 'Analytics'), ('Article', 'Article'), ('Books', 'Books'), ('Thesis', 'Thesis')], default='Nothing I guess', max_length=50),
        ),
        migrations.AlterField(
            model_name='reader',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
