# Generated by Django 5.2 on 2025-05-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0017_rename_book_editors_book_editors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Processing Borrow', 'Processing Borrow'), ('Processing Return', 'Processing Borrow'), ('Borrowed', 'Borrowed')], default='Available', max_length=20),
        ),
    ]
