# Generated by Django 5.2 on 2025-05-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0018_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_borrowed',
        ),
    ]
