# Generated by Django 5.2 on 2025-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0019_remove_book_is_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Processing Borrow', 'Processing Borrow'), ('Processing Return', 'Processing Return'), ('Borrowed', 'Borrowed')], default='Available', max_length=20),
        ),
    ]
