# Generated by Django 5.2 on 2025-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0021_fooditem_delete_account_delete_book_delete_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='scholarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='food_pic')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
