# Generated by Django 5.1.3 on 2025-05-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims_app", "0022_scholarlist_delete_fooditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="commenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=50)),
            ],
        ),
    ]
