# Generated by Django 5.1.3 on 2025-05-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims_app", "0023_commenter"),
    ]

    operations = [
        migrations.AddField(
            model_name="commenter",
            name="targetScholar",
            field=models.CharField(default="na", max_length=50),
            preserve_default=False,
        ),
    ]
