# Generated by Django 5.1.3 on 2025-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims_app", "0024_commenter_targetscholar"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarlist",
            name="section",
            field=models.CharField(
                choices=[
                    ("Polaris", "Polaris"),
                    ("Rigel", "Rigel"),
                    ("Sirius", "Sirius"),
                ],
                default="None",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
