# Generated by Django 5.1.3 on 2025-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims_app", "0025_scholarlist_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarlist",
            name="section",
            field=models.CharField(
                choices=[
                    ("Einstein", "Einstein"),
                    ("Tesla", "Tesla"),
                    ("Curie", "Curie"),
                ],
                max_length=50,
            ),
        ),
    ]
