# Generated by Django 5.2.1 on 2025-11-30 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0026_alter_scholarlist_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Comment', 'verbose_name_plural': 'Student Comments'},
        ),
        migrations.AlterModelOptions(
            name='scholarlist',
            options={'ordering': ['section', 'name'], 'verbose_name': 'Batch 2026 Student', 'verbose_name_plural': 'Batch 2026 Students'},
        ),
        migrations.AddField(
            model_name='commenter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scholarlist',
            name='favorite_memory',
            field=models.TextField(blank=True, help_text='Favorite school memory', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarlist',
            name='future_plans',
            field=models.CharField(blank=True, help_text='Plans after graduation', max_length=200),
        ),
        migrations.AddField(
            model_name='scholarlist',
            name='graduation_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='comment',
            field=models.TextField(help_text='Share your thoughts or memories', max_length=500),
        ),
        migrations.AlterField(
            model_name='commenter',
            name='targetScholar',
            field=models.CharField(help_text='Student this comment is for', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='description',
            field=models.TextField(help_text='Personal message, achievements, or memories', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='image',
            field=models.ImageField(help_text="Student's photo", upload_to='student_photos'),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='name',
            field=models.CharField(help_text="Student's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarlist',
            name='section',
            field=models.CharField(choices=[('Einstein', 'Einstein'), ('Tesla', 'Tesla'), ('Curie', 'Curie')], help_text="Student's section", max_length=50),
        ),
    ]
