# Generated by Django 6.0.2 on 2026-03-02 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0027_alter_commenter_options_alter_scholarlist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Your name', max_length=100)),
                ('sender_email', models.EmailField(blank=True, help_text='Your email (optional, for replies)', max_length=254)),
                ('message', models.TextField(help_text='Your private message', max_length=2000)),
                ('targetScholar', models.CharField(help_text='Student this message is for', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
