# Generated by Django 6.0.2 on 2026-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0028_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarlist',
            name='email',
            field=models.EmailField(blank=True, help_text="Student's email (for receiving private messages)", max_length=254),
        ),
    ]
